name: Snyk Open Source Test

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'master'

jobs:
  open-source-test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repo
          uses: actions/checkout@master

        - name: Setup dotnet
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '3.1'

        # - name: Install Dependencies
        #   run: dotnet restore

        - name: Test Open Source Dependencies with Snyk
          uses: snyk/actions/dotnet@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            command: test
            args: --all-projects